import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useGetCoach } from '@workspace/api-client-react';
import { useColors } from '@/hooks/useColors';
import { useBooking } from '@/context/BookingContext';
import { Button, EmptyState, ErrorState, LoadingState } from '@/components/AppUI';
export default function Coach() {
 const {coachId}=useLocalSearchParams<{coachId:string}>(); const colors=useColors(); const router=useRouter(); const {coach,slot,selectCoach,selectSlot}=useBooking(); const query=useGetCoach(coachId); const item=query.data ?? coach;
 if(query.isLoading&&!item)return <LoadingState/>; if(query.isError&&!item)return <ErrorState onRetry={()=>query.refetch()}/>; if(!item)return <EmptyState title="Coach not found"/>;
 return <ScrollView style={{backgroundColor:colors.background}} contentContainerStyle={styles.page}><View style={[styles.hero,{backgroundColor:item.accent||colors.accent}]}><Text style={[styles.initial,{color:colors.foreground}]}>{item.name.charAt(0)}</Text></View><View style={styles.heading}><View style={{flex:1}}><Text style={[styles.name,{color:colors.foreground}]}>{item.name}</Text><Text style={[styles.activity,{color:colors.primary}]}>{item.activity} · {item.area}</Text></View>{item.verified&&<View style={[styles.verified,{backgroundColor:colors.accent}]}><Feather name="check" size={14} color={colors.secondary}/><Text style={{color:colors.secondary,fontSize:11,fontWeight:'700'}}>Vetted</Text></View>}</View><Text style={[styles.description,{color:colors.mutedForeground}]}>{item.description}</Text><View style={[styles.stats,{borderColor:colors.border}]}><Stat label="Rating" value={`★ ${item.rating.toFixed(1)}`}/><Stat label="Experience" value={item.experience}/><Stat label="Age range" value={item.ageRange}/></View><Text style={[styles.section,{color:colors.foreground}]}>Why parents choose them</Text>{item.highlights.map((x)=><View key={x} style={styles.highlight}><Feather name="check-circle" size={18} color={colors.secondary}/><Text style={{color:colors.foreground,flex:1}}>{x}</Text></View>)}<Text style={[styles.section,{color:colors.foreground}]}>Pick a trial slot</Text><View style={styles.slots}>{item.slots.map((x)=><Pressable testID={`slot-${x.id}`} key={x.id} onPress={()=>{selectCoach(item);selectSlot(x)}} style={[styles.slot,{borderColor:slot?.id===x.id?colors.primary:colors.border,backgroundColor:slot?.id===x.id?colors.accent:colors.card}]}><Text style={{color:colors.foreground,fontWeight:'700'}}>{x.day}</Text><Text style={{color:colors.mutedForeground,fontSize:12,marginTop:3}}>{x.date} · {x.label}</Text></Pressable>)}</View><Button title="Book a trial" disabled={!slot} testID="book-trial" onPress={()=>router.push('/checkout')}/></ScrollView>;
}
function Stat({label,value}:{label:string,value:string}){const c=useColors();return <View style={{flex:1}}><Text style={{color:c.foreground,fontWeight:'700',fontSize:13}}>{value}</Text><Text style={{color:c.mutedForeground,fontSize:11,marginTop:3}}>{label}</Text></View>}
const styles=StyleSheet.create({page:{padding:20,paddingBottom:40},hero:{height:180,borderRadius:26,alignItems:'center',justifyContent:'center'},initial:{fontSize:76,fontWeight:'800'},heading:{flexDirection:'row',alignItems:'center',marginTop:20},name:{fontSize:26,fontWeight:'800'},activity:{fontSize:14,fontWeight:'600',marginTop:5},verified:{paddingHorizontal:9,paddingVertical:6,borderRadius:14,flexDirection:'row',gap:4,alignItems:'center'},description:{fontSize:14,lineHeight:22,marginTop:16},stats:{flexDirection:'row',paddingVertical:18,marginTop:13,borderTopWidth:1,borderBottomWidth:1},section:{fontSize:18,fontWeight:'800',marginTop:25,marginBottom:14},highlight:{flexDirection:'row',gap:10,alignItems:'center',marginBottom:12},slots:{gap:10},slot:{borderWidth:1,borderRadius:16,padding:14},});