import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useCreateBooking } from '@workspace/api-client-react';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { useBooking } from '@/context/BookingContext';
import { useColors } from '@/hooks/useColors';
import { Button } from '@/components/AppUI';
export default function Checkout(){const c=useColors();const router=useRouter();const {coach,slot}=useBooking();const mutation=useCreateBooking();const [form,setForm]=useState({childName:'',childAge:'',parentName:'',parentEmail:'',parentPhone:''});const update=(key:string,v:string)=>setForm(x=>({...x,[key]:v}));const submit=()=>{if(!coach||!slot||!form.childName||!form.childAge||!form.parentName||!form.parentEmail||!form.parentPhone){Alert.alert('Almost there','Please complete every field.');return}mutation.mutate({data:{coachId:coach.id,slotId:slot.id,childName:form.childName,childAge:Number(form.childAge),parentName:form.parentName,parentEmail:form.parentEmail,parentPhone:form.parentPhone}},{onSuccess:(booking)=>router.replace(`/confirmation/${booking.id}`),onError:()=>Alert.alert('Booking failed','We could not complete your booking. Please try again.')})};if(!coach||!slot)return <View style={[styles.center,{backgroundColor:c.background}]}><Text style={{color:c.foreground}}>Choose a coach and slot first.</Text></View>;return <KeyboardAwareScrollViewCompat style={{backgroundColor:c.background}} contentContainerStyle={[styles.page,{paddingBottom:30}]} bottomOffset={70} keyboardShouldPersistTaps="handled"><Text style={[styles.title,{color:c.foreground}]}>Your trial, sorted.</Text><Text style={{color:c.mutedForeground,marginBottom:20}}>{coach.name} · {slot.day}, {slot.date} at {slot.label}</Text><Text style={[styles.section,{color:c.foreground}]}>About your child</Text><Field label="Child’s name" value={form.childName} onChangeText={v=>update('childName',v)} colors={c}/><Field label="Age" keyboardType="number-pad" value={form.childAge} onChangeText={v=>update('childAge',v)} colors={c}/><Text style={[styles.section,{color:c.foreground}]}>Parent details</Text><Field label="Your name" value={form.parentName} onChangeText={v=>update('parentName',v)} colors={c}/><Field label="Email address" keyboardType="email-address" autoCapitalize="none" value={form.parentEmail} onChangeText={v=>update('parentEmail',v)} colors={c}/><Field label="Phone number" keyboardType="phone-pad" value={form.parentPhone} onChangeText={v=>update('parentPhone',v)} colors={c}/><View style={[styles.breakdown,{backgroundColor:c.card,borderColor:c.border}]}><Text style={[styles.section,{color:c.foreground,marginTop:0}]}>Fee breakdown</Text><Line label="Trial fee" value={`₹${coach.price.toLocaleString('en-IN')}`} colors={c}/><Line label="Service fee" value="₹49" colors={c}/><Line label="Total" value={`₹${(coach.price+49).toLocaleString('en-IN')}`} colors={c} bold/></View><View style={styles.secure}><Feather name="lock" size={16} color={c.secondary}/><Text style={{color:c.mutedForeground,fontSize:12,flex:1}}>Secure payment. You’ll only be charged after confirming.</Text></View><Button title={mutation.isPending?'Confirming…':'Confirm and pay'} disabled={mutation.isPending} testID="confirm-booking" onPress={submit}/></KeyboardAwareScrollViewCompat>}
function Field({label,colors,...p}:{label:string;colors:any}&TextInputProps){return <TextInput placeholder={label} placeholderTextColor={colors.mutedForeground} style={[styles.field,{backgroundColor:colors.card,borderColor:colors.input,color:colors.foreground}]} {...p}/>}
function Line({label,value,colors,bold}:{label:string;value:string;colors:any;bold?:boolean}){return <View style={styles.line}><Text style={{color:colors.mutedForeground,fontWeight:bold?'700':'400'}}>{label}</Text><Text style={{color:colors.foreground,fontWeight:bold?'800':'600'}}>{value}</Text></View>}
const styles=StyleSheet.create({page:{padding:20},center:{flex:1,alignItems:'center',justifyContent:'center'},title:{fontSize:29,fontWeight:'800',marginBottom:7},section:{fontSize:18,fontWeight:'800',marginTop:8,marginBottom:12},field:{height:52,borderWidth:1,borderRadius:16,paddingHorizontal:15,fontSize:15,marginBottom:11},breakdown:{borderWidth:1,borderRadius:20,padding:17,marginTop:13},line:{flexDirection:'row',justifyContent:'space-between',paddingVertical:7},secure:{flexDirection:'row',gap:8,alignItems:'center',marginVertical:17}});