import React, { useState } from 'react';
import { Keyboard, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

const examples = ['Swimming lessons', 'Dance classes', 'Football coaching'];
export default function Home() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const router = useRouter();
  const [query, setQuery] = useState('');
  const go = (value = query) => { if (!value.trim()) return; Haptics.selectionAsync(); Keyboard.dismiss(); router.push({ pathname: '/results', params: { q: value } }); };
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.home, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + (Platform.OS === 'web' ? 34 : 28) }]} keyboardShouldPersistTaps="handled">
    <View style={styles.brand}><View style={[styles.logo, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontWeight: '800', fontSize: 20 }}>d</Text></View><Text style={[styles.wordmark, { color: colors.foreground }]}>dabble</Text></View>
    <View style={styles.hero}><Text style={[styles.kicker, { color: colors.secondary }]}>MAKE TIME FOR WHAT THEY LOVE</Text><Text style={[styles.title, { color: colors.foreground }]}>Find their next{'\n'}<Text style={{ color: colors.primary }}>favourite thing.</Text></Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Vetted coaches and classes for curious kids in Bangalore.</Text></View>
    <View style={[styles.searchBox, { backgroundColor: colors.card, borderColor: colors.input }]}><Feather name="search" size={21} color={colors.mutedForeground} /><TextInput testID="home-search" value={query} onChangeText={setQuery} onSubmitEditing={() => go()} returnKeyType="search" placeholder="swimming for my 7-year-old near Whitefield, weekend mornings" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} multiline /></View>
    <Pressable testID="search-button" onPress={() => go()} style={[styles.searchButton, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontWeight: '700' }}>Find a coach</Text><Feather name="arrow-up-right" size={19} color={colors.primaryForeground} /></Pressable>
    <Text style={[styles.label, { color: colors.mutedForeground }]}>Try an example</Text><View style={styles.chips}>{examples.map((example) => <Pressable testID={`example-${example}`} key={example} onPress={() => { setQuery(example); go(example); }} style={[styles.chip, { backgroundColor: colors.accent }]}><Text style={{ color: colors.accentForeground, fontSize: 13 }}>{example}</Text></Pressable>)}</View>
    <Pressable testID="guide-button" onPress={() => router.push({ pathname: '/results', params: { q: 'I need help choosing an activity for my child' } })} style={[styles.guide, { backgroundColor: colors.secondary }]}><View><Text style={{ color: colors.secondaryForeground, fontWeight: '700', fontSize: 15 }}>Not sure? Guide me</Text><Text style={{ color: colors.secondaryForeground, opacity: 0.8, marginTop: 4, fontSize: 12 }}>Answer three quick questions</Text></View><Feather name="arrow-right" size={20} color={colors.secondaryForeground} /></Pressable>
    <View style={[styles.trust, { borderTopColor: colors.border }]}><Feather name="shield" size={17} color={colors.secondary} /><Text style={{ color: colors.mutedForeground, fontSize: 12, flex: 1 }}>Every coach is vetted · Book a trial · Pay securely</Text></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ home: { paddingHorizontal: 22 }, brand: { flexDirection: 'row', alignItems: 'center', gap: 9 }, logo: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, wordmark: { fontSize: 20, fontWeight: '800', letterSpacing: -0.8 }, hero: { marginTop: 62, marginBottom: 25 }, kicker: { fontSize: 11, fontWeight: '800', letterSpacing: 1.3, marginBottom: 14 }, title: { fontSize: 37, lineHeight: 43, fontWeight: '800', letterSpacing: -1.2 }, subtitle: { marginTop: 15, fontSize: 15, lineHeight: 22 }, searchBox: { minHeight: 92, borderWidth: 1, borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'flex-start', gap: 11 }, input: { flex: 1, fontSize: 15, lineHeight: 21, padding: 0 }, searchButton: { marginTop: 10, height: 52, borderRadius: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, label: { fontSize: 12, marginTop: 29, marginBottom: 11 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderRadius: 18, paddingVertical: 11, paddingHorizontal: 14 }, guide: { borderRadius: 20, marginTop: 30, padding: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, trust: { flexDirection: 'row', gap: 9, paddingTop: 21, marginTop: 24, borderTopWidth: 1, alignItems: 'center' } });